export const DRAWIO_AWS_SHAPES: Record<string, string> = {
  'lambda':             'mxgraph.aws4.lambda_function',
  'api-gateway':        'mxgraph.aws4.api_gateway',
  'api-gateway-v2':     'mxgraph.aws4.api_gateway',
  'dynamodb':           'mxgraph.aws4.dynamodb',
  's3':                 'mxgraph.aws4.s3',
  'sqs':                'mxgraph.aws4.sqs',
  'sns':                'mxgraph.aws4.sns',
  'cloudfront':         'mxgraph.aws4.cloudfront',
  'ecs':                'mxgraph.aws4.ecs',
  'ecs-fargate':        'mxgraph.aws4.fargate',
  'eks':                'mxgraph.aws4.eks',
  'ec2':                'mxgraph.aws4.ec2',
  'rds':                'mxgraph.aws4.rds',
  'rds-mysql':          'mxgraph.aws4.rds_mysql_instance',
  'rds-postgres':       'mxgraph.aws4.rds_postgresql_instance',
  'aurora':             'mxgraph.aws4.aurora',
  'aurora-serverless':  'mxgraph.aws4.aurora',
  'elasticache':        'mxgraph.aws4.elasticache',
  'elasticache-memcached': 'mxgraph.aws4.elasticache',
  'alb':                'mxgraph.aws4.application_load_balancer',
  'nlb':                'mxgraph.aws4.network_load_balancer',
  'cognito':            'mxgraph.aws4.cognito',
  'eventbridge':        'mxgraph.aws4.eventbridge',
  'step-functions':     'mxgraph.aws4.step_functions',
  'kinesis':            'mxgraph.aws4.kinesis_data_streams',
  'kinesis-firehose':   'mxgraph.aws4.kinesis_firehose',
  'cloudwatch':         'mxgraph.aws4.cloudwatch',
  'route53':            'mxgraph.aws4.route_53',
  'waf':                'mxgraph.aws4.waf',
  'msk':                'mxgraph.aws4.managed_streaming_for_kafka',
  'bedrock':            'mxgraph.aws4.bedrock',
  'sagemaker':          'mxgraph.aws4.sagemaker',
  'neptune':            'mxgraph.aws4.neptune',
  'opensearch':         'mxgraph.aws4.opensearch_service',
  'redshift':           'mxgraph.aws4.redshift',
  'app-runner':         'mxgraph.aws4.app_runner',
  'xray':               'mxgraph.aws4.xray',
  'global-accelerator': 'mxgraph.aws4.global_accelerator',
  'batch':              'mxgraph.aws4.batch',
  'iam':                'mxgraph.aws4.role',
  'internet':           'mxgraph.aws4.internet_gateway',
  'users':              'mxgraph.aws4.user',
  'timestream':         'mxgraph.aws4.timestream',
  'app-mesh':           'mxgraph.aws4.app_mesh',
};

export function getAwsShape(service: string): string {
  return DRAWIO_AWS_SHAPES[service] ?? 'mxgraph.aws4.traditional_server';
}
